import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: false,
  jsonMode: true,
  objectGeneration: true,
  reasoning: false,
  embedding: false,
} as const;

export const anthropicModels: Record<string, ModelDefinition> = {
  "claude-fable-5": {
    id: "claude-fable-5",
    provider: "anthropic",
    name: "Claude Fable 5",
    description: "Anthropic's frontier model for advanced reasoning and creative tasks.",
    resourceType: "chat",
    family: "claude-5",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      reasoning: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 5.0,
      outputTokensPerMillion: 25.0,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["claude-5-fable"],
  },
  "claude-opus-4-8": {
    id: "claude-opus-4-8",
    provider: "anthropic",
    name: "Claude Opus 4.8",
    description: "Anthropic's most capable model for complex reasoning and coding.",
    resourceType: "chat",
    family: "claude-5",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      reasoning: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 15.0,
      outputTokensPerMillion: 75.0,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["claude-5-opus"],
  },
  "claude-sonnet-5": {
    id: "claude-sonnet-5",
    provider: "anthropic",
    name: "Claude Sonnet 5",
    description: "Balanced Claude 5 model for general-purpose reasoning and coding.",
    resourceType: "chat",
    family: "claude-5",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 3.0,
      outputTokensPerMillion: 15.0,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["claude-5-sonnet"],
  },
  "claude-haiku-4-5": {
    id: "claude-haiku-4-5",
    provider: "anthropic",
    name: "Claude Haiku 4.5",
    description: "Fast, cost-effective Claude 5 model for everyday tasks.",
    resourceType: "chat",
    family: "claude-5",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 1.0,
      outputTokensPerMillion: 5.0,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["claude-5-haiku"],
  },
  "claude-3-5-sonnet-20241022": {
    id: "claude-3-5-sonnet-20241022",
    provider: "anthropic",
    name: "Claude 3.5 Sonnet",
    description: "Anthropic's balanced model for complex reasoning and coding.",
    resourceType: "chat",
    family: "claude-3",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
    },
    pricing: {
      inputTokensPerMillion: 3.0,
      outputTokensPerMillion: 15.0,
    },
    contextWindow: 200_000,
    maxOutputTokens: 8192,
  },
  "claude-3-5-haiku-20241022": {
    id: "claude-3-5-haiku-20241022",
    provider: "anthropic",
    name: "Claude 3.5 Haiku",
    description: "Fast, cost-effective Anthropic model for everyday tasks.",
    resourceType: "chat",
    family: "claude-3",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      vision: false,
      functionCalling: true,
    },
    pricing: {
      inputTokensPerMillion: 1.0,
      outputTokensPerMillion: 5.0,
    },
    contextWindow: 200_000,
    maxOutputTokens: 8192,
  },
  "claude-3-opus-20240229": {
    id: "claude-3-opus-20240229",
    provider: "anthropic",
    name: "Claude 3 Opus",
    description: "Anthropic's most capable model for highly complex tasks.",
    resourceType: "chat",
    family: "claude-3",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
    },
    pricing: {
      inputTokensPerMillion: 15.0,
      outputTokensPerMillion: 75.0,
    },
    contextWindow: 200_000,
    maxOutputTokens: 4096,
  },
  "claude-3-sonnet-20240229": {
    id: "claude-3-sonnet-20240229",
    provider: "anthropic",
    name: "Claude 3 Sonnet",
    description: "Previous-generation balanced Anthropic model.",
    resourceType: "chat",
    family: "claude-3",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
    },
    pricing: {
      inputTokensPerMillion: 3.0,
      outputTokensPerMillion: 15.0,
    },
    contextWindow: 200_000,
    maxOutputTokens: 4096,
  },
  "claude-3-haiku-20240307": {
    id: "claude-3-haiku-20240307",
    provider: "anthropic",
    name: "Claude 3 Haiku",
    description: "Previous-generation fast Anthropic model.",
    resourceType: "chat",
    family: "claude-3",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
    },
    pricing: {
      inputTokensPerMillion: 0.25,
      outputTokensPerMillion: 1.25,
    },
    contextWindow: 200_000,
    maxOutputTokens: 4096,
  },
};

export type AnthropicModelId = keyof typeof anthropicModels;
