import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: true,
  functionCalling: true,
  jsonMode: true,
  objectGeneration: true,
  reasoning: false,
  embedding: false,
  structuredOutputs: true,
  supportsJSON: true,
} as const;

export const geminiModels: Record<string, ModelDefinition> = {
  "gemini-2.5-pro": {
    id: "gemini-2.5-pro",
    provider: "gemini",
    name: "Gemini 2.5 Pro",
    description: "Google's most capable Gemini model for complex reasoning and multimodal tasks.",
    resourceType: "chat",
    family: "gemini-2.5",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      reasoning: true,
    },
    pricing: {
      inputTokensPerMillion: 1.25,
      outputTokensPerMillion: 10.0,
    },
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    aliases: ["gemini-pro"],
  },
  "gemini-2.5-flash": {
    id: "gemini-2.5-flash",
    provider: "gemini",
    name: "Gemini 2.5 Flash",
    description: "Fast, cost-efficient Gemini model for high-throughput tasks.",
    resourceType: "chat",
    family: "gemini-2.5",
    status: "active",
    capabilities: chatCapabilities,
    pricing: {
      inputTokensPerMillion: 0.3,
      outputTokensPerMillion: 2.5,
    },
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    aliases: ["gemini-flash"],
  },
  "gemini-2.5-flash-lite": {
    id: "gemini-2.5-flash-lite",
    provider: "gemini",
    name: "Gemini 2.5 Flash Lite",
    description: "Lightweight Gemini model for simple, high-volume tasks.",
    resourceType: "chat",
    family: "gemini-2.5",
    status: "active",
    capabilities: chatCapabilities,
    pricing: {
      inputTokensPerMillion: 0.1,
      outputTokensPerMillion: 0.4,
    },
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
  },
  "gemini-3.1-pro-preview": {
    id: "gemini-3.1-pro-preview",
    provider: "gemini",
    name: "Gemini 3.1 Pro Preview",
    description: "Preview of Google's next-generation Gemini Pro model.",
    resourceType: "chat",
    family: "gemini-3",
    status: "preview",
    capabilities: {
      ...chatCapabilities,
      reasoning: true,
    },
    contextWindow: 2_097_152,
    maxOutputTokens: 65_536,
  },
  "gemini-3.5-flash": {
    id: "gemini-3.5-flash",
    provider: "gemini",
    name: "Gemini 3.5 Flash",
    description: "Next-generation fast Gemini model.",
    resourceType: "chat",
    family: "gemini-3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 2_097_152,
    maxOutputTokens: 65_536,
  },
  "gemini-3.1-flash-lite": {
    id: "gemini-3.1-flash-lite",
    provider: "gemini",
    name: "Gemini 3.1 Flash Lite",
    description: "Lightweight next-generation Gemini model.",
    resourceType: "chat",
    family: "gemini-3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 2_097_152,
    maxOutputTokens: 65_536,
  },
  "gemini-3-flash-preview": {
    id: "gemini-3-flash-preview",
    provider: "gemini",
    name: "Gemini 3 Flash Preview",
    description: "Preview of the Gemini 3 Flash model.",
    resourceType: "chat",
    family: "gemini-3",
    status: "preview",
    capabilities: chatCapabilities,
    contextWindow: 2_097_152,
    maxOutputTokens: 65_536,
  },
};

export type GeminiModelId = keyof typeof geminiModels;
