import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: true,
  jsonMode: true,
  objectGeneration: true,
  reasoning: false,
  embedding: false,
  structuredOutputs: true,
  supportsJSON: true,
} as const;

export const kimiModels: Record<string, ModelDefinition> = {
  "kimi-k3": {
    id: "kimi-k3",
    provider: "kimi",
    name: "Kimi K3",
    description: "Moonshot AI's flagship Kimi K3 model for advanced reasoning and coding.",
    resourceType: "chat",
    family: "kimi-k3",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      reasoning: true,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["kimi-latest"],
  },
  "kimi-k2.7-code": {
    id: "kimi-k2.7-code",
    provider: "kimi",
    name: "Kimi K2.7 Code",
    description: "Kimi K2.7 optimized for code generation and software engineering tasks.",
    resourceType: "chat",
    family: "kimi-k2.7",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "kimi-k2.7-code-highspeed": {
    id: "kimi-k2.7-code-highspeed",
    provider: "kimi",
    name: "Kimi K2.7 Code Highspeed",
    description: "High-throughput variant of Kimi K2.7 Code.",
    resourceType: "chat",
    family: "kimi-k2.7",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "kimi-k2.6": {
    id: "kimi-k2.6",
    provider: "kimi",
    name: "Kimi K2.6",
    description: "Kimi K2.6 general-purpose chat model.",
    resourceType: "chat",
    family: "kimi-k2.6",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "kimi-k2.5": {
    id: "kimi-k2.5",
    provider: "kimi",
    name: "Kimi K2.5",
    description: "Kimi K2.5 general-purpose chat model.",
    resourceType: "chat",
    family: "kimi-k2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "moonshot-v1-8k": {
    id: "moonshot-v1-8k",
    provider: "kimi",
    name: "Moonshot v1 8K",
    description: "Moonshot v1 with 8K context window.",
    resourceType: "chat",
    family: "moonshot-v1",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 8192,
    maxOutputTokens: 4096,
  },
  "moonshot-v1-32k": {
    id: "moonshot-v1-32k",
    provider: "kimi",
    name: "Moonshot v1 32K",
    description: "Moonshot v1 with 32K context window.",
    resourceType: "chat",
    family: "moonshot-v1",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "moonshot-v1-128k": {
    id: "moonshot-v1-128k",
    provider: "kimi",
    name: "Moonshot v1 128K",
    description: "Moonshot v1 with 128K context window.",
    resourceType: "chat",
    family: "moonshot-v1",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 131_072,
    maxOutputTokens: 4096,
  },
  "moonshot-v1-8k-vision-preview": {
    id: "moonshot-v1-8k-vision-preview",
    provider: "kimi",
    name: "Moonshot v1 8K Vision Preview",
    description: "Moonshot v1 8K with vision support (preview).",
    resourceType: "chat",
    family: "moonshot-v1",
    status: "preview",
    capabilities: {
      ...chatCapabilities,
      vision: true,
    },
    contextWindow: 8192,
    maxOutputTokens: 4096,
  },
  "moonshot-v1-32k-vision-preview": {
    id: "moonshot-v1-32k-vision-preview",
    provider: "kimi",
    name: "Moonshot v1 32K Vision Preview",
    description: "Moonshot v1 32K with vision support (preview).",
    resourceType: "chat",
    family: "moonshot-v1",
    status: "preview",
    capabilities: {
      ...chatCapabilities,
      vision: true,
    },
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "moonshot-v1-128k-vision-preview": {
    id: "moonshot-v1-128k-vision-preview",
    provider: "kimi",
    name: "Moonshot v1 128K Vision Preview",
    description: "Moonshot v1 128K with vision support (preview).",
    resourceType: "chat",
    family: "moonshot-v1",
    status: "preview",
    capabilities: {
      ...chatCapabilities,
      vision: true,
    },
    contextWindow: 131_072,
    maxOutputTokens: 4096,
  },
};

export type KimiModelId = keyof typeof kimiModels;
