import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: false,
  jsonMode: false,
  objectGeneration: false,
  reasoning: false,
  embedding: false,
} as const;

const embeddingCapabilities = {
  chat: false,
  streaming: false,
  vision: false,
  functionCalling: false,
  jsonMode: false,
  objectGeneration: false,
  reasoning: false,
  embedding: true,
} as const;

export const openaiModels: Record<string, ModelDefinition> = {
  "gpt-5.6-sol": {
    id: "gpt-5.6-sol",
    provider: "openai",
    name: "GPT-5.6 Sol",
    description: "OpenAI's flagship frontier model for complex reasoning and multimodal tasks.",
    resourceType: "chat",
    family: "gpt-5.6",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      reasoning: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 5.0,
      outputTokensPerMillion: 20.0,
      cachedInputTokensPerMillion: 2.5,
    },
    contextWindow: 256_000,
    maxOutputTokens: 32_768,
    aliases: ["gpt5.6-sol", "gpt-5.6-flagship"],
  },
  "gpt-5.6-terra": {
    id: "gpt-5.6-terra",
    provider: "openai",
    name: "GPT-5.6 Terra",
    description: "Balanced GPT-5.6 variant optimized for coding and general-purpose tasks.",
    resourceType: "chat",
    family: "gpt-5.6",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      reasoning: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 3.0,
      outputTokensPerMillion: 12.0,
      cachedInputTokensPerMillion: 1.5,
    },
    contextWindow: 256_000,
    maxOutputTokens: 32_768,
    aliases: ["gpt5.6-terra", "gpt-5.6-balanced"],
  },
  "gpt-5.6-luna": {
    id: "gpt-5.6-luna",
    provider: "openai",
    name: "GPT-5.6 Luna",
    description: "Fast, cost-efficient GPT-5.6 variant for high-throughput workloads.",
    resourceType: "chat",
    family: "gpt-5.6",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 1.5,
      outputTokensPerMillion: 6.0,
      cachedInputTokensPerMillion: 0.75,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    aliases: ["gpt5.6-luna", "gpt-5.6-fast"],
  },
  "gpt-4o": {
    id: "gpt-4o",
    provider: "openai",
    name: "GPT-4o",
    description: "OpenAI's most capable multimodal flagship model.",
    resourceType: "chat",
    family: "gpt-4o",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 2.5,
      outputTokensPerMillion: 10.0,
      cachedInputTokensPerMillion: 1.25,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
  },
  "gpt-4o-mini": {
    id: "gpt-4o-mini",
    provider: "openai",
    name: "GPT-4o mini",
    description: "Fast, affordable small model for focused tasks.",
    resourceType: "chat",
    family: "gpt-4o",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      structuredOutputs: true,
      supportsJSON: true,
    },
    pricing: {
      inputTokensPerMillion: 0.15,
      outputTokensPerMillion: 0.6,
      cachedInputTokensPerMillion: 0.075,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
  },
  "gpt-4-turbo": {
    id: "gpt-4-turbo",
    provider: "openai",
    name: "GPT-4 Turbo",
    description: "Previous-generation GPT-4 with vision and tool support.",
    resourceType: "chat",
    family: "gpt-4",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 10.0,
      outputTokensPerMillion: 30.0,
    },
    contextWindow: 128_000,
    maxOutputTokens: 4096,
  },
  "gpt-4": {
    id: "gpt-4",
    provider: "openai",
    name: "GPT-4",
    description: "Original GPT-4 model.",
    resourceType: "chat",
    family: "gpt-4",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 30.0,
      outputTokensPerMillion: 60.0,
    },
    contextWindow: 8192,
    maxOutputTokens: 8192,
  },
  "gpt-3.5-turbo": {
    id: "gpt-3.5-turbo",
    provider: "openai",
    name: "GPT-3.5 Turbo",
    description: "Cost-effective model for simple tasks.",
    resourceType: "chat",
    family: "gpt-3.5",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 0.5,
      outputTokensPerMillion: 1.5,
    },
    contextWindow: 16_385,
    maxOutputTokens: 4096,
  },
  o1: {
    id: "o1",
    provider: "openai",
    name: "o1",
    description: "Reasoning model designed for complex problems.",
    resourceType: "chat",
    family: "o1",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      streaming: false,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      reasoning: true,
    },
    pricing: {
      inputTokensPerMillion: 15.0,
      outputTokensPerMillion: 60.0,
      cachedInputTokensPerMillion: 7.5,
    },
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
  },
  "o3-mini": {
    id: "o3-mini",
    provider: "openai",
    name: "o3-mini",
    description: "Small reasoning model for STEM and logic tasks.",
    resourceType: "chat",
    family: "o3",
    status: "deprecated",
    capabilities: {
      ...chatCapabilities,
      streaming: false,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      reasoning: true,
    },
    pricing: {
      inputTokensPerMillion: 1.1,
      outputTokensPerMillion: 4.4,
      cachedInputTokensPerMillion: 0.55,
    },
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
  },
  "text-embedding-3-small": {
    id: "text-embedding-3-small",
    provider: "openai",
    name: "text-embedding-3-small",
    description: "Efficient embedding model for search and clustering.",
    resourceType: "embedding",
    status: "active",
    capabilities: embeddingCapabilities,
    pricing: {
      inputTokensPerMillion: 0.02,
      outputTokensPerMillion: 0,
    },
    contextWindow: 8192,
  },
  "text-embedding-3-large": {
    id: "text-embedding-3-large",
    provider: "openai",
    name: "text-embedding-3-large",
    description: "High-performance embedding model.",
    resourceType: "embedding",
    status: "active",
    capabilities: embeddingCapabilities,
    pricing: {
      inputTokensPerMillion: 0.13,
      outputTokensPerMillion: 0,
    },
    contextWindow: 8192,
  },
  "text-embedding-ada-002": {
    id: "text-embedding-ada-002",
    provider: "openai",
    name: "text-embedding-ada-002",
    description: "Legacy OpenAI embedding model.",
    resourceType: "embedding",
    status: "deprecated",
    capabilities: embeddingCapabilities,
    pricing: {
      inputTokensPerMillion: 0.1,
      outputTokensPerMillion: 0,
    },
    contextWindow: 8192,
  },
};

export type OpenAIModelId = keyof typeof openaiModels;
