import type { ModelDefinition } from "../types.js";

const capabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: false,
  jsonMode: false,
  objectGeneration: false,
  reasoning: false,
  embedding: false,
} as const;

export const openaiModels: Record<string, ModelDefinition> = {
  "gpt-4o": {
    id: "gpt-4o",
    provider: "openai",
    name: "GPT-4o",
    description: "OpenAI's most capable multimodal flagship model.",
    capabilities: {
      ...capabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 2.5,
      outputTokensPerMillion: 10.0,
      cachedInputTokensPerMillion: 1.25,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
  },
  "gpt-4o-mini": {
    id: "gpt-4o-mini",
    provider: "openai",
    name: "GPT-4o mini",
    description: "Fast, affordable small model for focused tasks.",
    capabilities: {
      ...capabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 0.15,
      outputTokensPerMillion: 0.6,
      cachedInputTokensPerMillion: 0.075,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
  },
  "gpt-4-turbo": {
    id: "gpt-4-turbo",
    provider: "openai",
    name: "GPT-4 Turbo",
    description: "Previous-generation GPT-4 with vision and tool support.",
    capabilities: {
      ...capabilities,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 10.0,
      outputTokensPerMillion: 30.0,
    },
    contextWindow: 128_000,
    maxOutputTokens: 4096,
  },
  "gpt-4": {
    id: "gpt-4",
    provider: "openai",
    name: "GPT-4",
    description: "Original GPT-4 model.",
    capabilities: {
      ...capabilities,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 30.0,
      outputTokensPerMillion: 60.0,
    },
    contextWindow: 8192,
    maxOutputTokens: 8192,
  },
  "gpt-3.5-turbo": {
    id: "gpt-3.5-turbo",
    provider: "openai",
    name: "GPT-3.5 Turbo",
    description: "Cost-effective model for simple tasks.",
    capabilities: {
      ...capabilities,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
    },
    pricing: {
      inputTokensPerMillion: 0.5,
      outputTokensPerMillion: 1.5,
    },
    contextWindow: 16_385,
    maxOutputTokens: 4096,
  },
  o1: {
    id: "o1",
    provider: "openai",
    name: "o1",
    description: "Reasoning model designed for complex problems.",
    capabilities: {
      ...capabilities,
      streaming: false,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      reasoning: true,
    },
    pricing: {
      inputTokensPerMillion: 15.0,
      outputTokensPerMillion: 60.0,
      cachedInputTokensPerMillion: 7.5,
    },
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
  },
  "o3-mini": {
    id: "o3-mini",
    provider: "openai",
    name: "o3-mini",
    description: "Small reasoning model for STEM and logic tasks.",
    capabilities: {
      ...capabilities,
      streaming: false,
      functionCalling: true,
      jsonMode: true,
      objectGeneration: true,
      reasoning: true,
    },
    pricing: {
      inputTokensPerMillion: 1.1,
      outputTokensPerMillion: 4.4,
      cachedInputTokensPerMillion: 0.55,
    },
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
  },
  "text-embedding-3-small": {
    id: "text-embedding-3-small",
    provider: "openai",
    name: "text-embedding-3-small",
    description: "Efficient embedding model for search and clustering.",
    capabilities: {
      ...capabilities,
      chat: false,
      streaming: false,
      embedding: true,
    },
    pricing: {
      inputTokensPerMillion: 0.02,
      outputTokensPerMillion: 0,
    },
    contextWindow: 8192,
  },
  "text-embedding-3-large": {
    id: "text-embedding-3-large",
    provider: "openai",
    name: "text-embedding-3-large",
    description: "High-performance embedding model.",
    capabilities: {
      ...capabilities,
      chat: false,
      streaming: false,
      embedding: true,
    },
    pricing: {
      inputTokensPerMillion: 0.13,
      outputTokensPerMillion: 0,
    },
    contextWindow: 8192,
  },
  "text-embedding-ada-002": {
    id: "text-embedding-ada-002",
    provider: "openai",
    name: "text-embedding-ada-002",
    description: "Legacy OpenAI embedding model.",
    capabilities: {
      ...capabilities,
      chat: false,
      streaming: false,
      embedding: true,
    },
    pricing: {
      inputTokensPerMillion: 0.1,
      outputTokensPerMillion: 0,
    },
    contextWindow: 8192,
  },
};

export type OpenAIModelId = keyof typeof openaiModels;
