import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: true,
  jsonMode: true,
  objectGeneration: true,
  reasoning: false,
  embedding: false,
  structuredOutputs: true,
  supportsJSON: true,
} as const;

const visionCapabilities = {
  ...chatCapabilities,
  vision: true,
} as const;

export const qwenModels: Record<string, ModelDefinition> = {
  "qwen3.6-27b": {
    id: "qwen3.6-27b",
    provider: "qwen",
    name: "Qwen 3.6 27B",
    description: "Qwen 3.6 flagship model for reasoning and coding.",
    resourceType: "chat",
    family: "qwen3.6",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      reasoning: true,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["qwen-latest"],
  },
  "qwen3-0.6b": {
    id: "qwen3-0.6b",
    provider: "qwen",
    name: "Qwen 3 0.6B",
    description: "Qwen 3 small model for edge and low-latency tasks.",
    resourceType: "chat",
    family: "qwen3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "qwen3-1.7b": {
    id: "qwen3-1.7b",
    provider: "qwen",
    name: "Qwen 3 1.7B",
    description: "Qwen 3 small model for edge and low-latency tasks.",
    resourceType: "chat",
    family: "qwen3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "qwen3-4b": {
    id: "qwen3-4b",
    provider: "qwen",
    name: "Qwen 3 4B",
    description: "Qwen 3 compact model balancing speed and capability.",
    resourceType: "chat",
    family: "qwen3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen3-8b": {
    id: "qwen3-8b",
    provider: "qwen",
    name: "Qwen 3 8B",
    description: "Qwen 3 mid-size model for general-purpose tasks.",
    resourceType: "chat",
    family: "qwen3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen3-14b": {
    id: "qwen3-14b",
    provider: "qwen",
    name: "Qwen 3 14B",
    description: "Qwen 3 mid-size model for general-purpose tasks.",
    resourceType: "chat",
    family: "qwen3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen3-32b": {
    id: "qwen3-32b",
    provider: "qwen",
    name: "Qwen 3 32B",
    description: "Qwen 3 large model for complex reasoning.",
    resourceType: "chat",
    family: "qwen3",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-0.5b": {
    id: "qwen2.5-0.5b",
    provider: "qwen",
    name: "Qwen 2.5 0.5B",
    description: "Qwen 2.5 small model for edge tasks.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "qwen2.5-1.5b": {
    id: "qwen2.5-1.5b",
    provider: "qwen",
    name: "Qwen 2.5 1.5B",
    description: "Qwen 2.5 small model for edge tasks.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "qwen2.5-3b": {
    id: "qwen2.5-3b",
    provider: "qwen",
    name: "Qwen 2.5 3B",
    description: "Qwen 2.5 compact model.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-7b": {
    id: "qwen2.5-7b",
    provider: "qwen",
    name: "Qwen 2.5 7B",
    description: "Qwen 2.5 mid-size model.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-14b": {
    id: "qwen2.5-14b",
    provider: "qwen",
    name: "Qwen 2.5 14B",
    description: "Qwen 2.5 mid-size model.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-32b": {
    id: "qwen2.5-32b",
    provider: "qwen",
    name: "Qwen 2.5 32B",
    description: "Qwen 2.5 large model.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-72b": {
    id: "qwen2.5-72b",
    provider: "qwen",
    name: "Qwen 2.5 72B",
    description: "Qwen 2.5 large model for complex reasoning.",
    resourceType: "chat",
    family: "qwen2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-coder-1.5b": {
    id: "qwen2.5-coder-1.5b",
    provider: "qwen",
    name: "Qwen 2.5 Coder 1.5B",
    description: "Qwen 2.5 Coder small model for code generation.",
    resourceType: "chat",
    family: "qwen2.5-coder",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-coder-7b": {
    id: "qwen2.5-coder-7b",
    provider: "qwen",
    name: "Qwen 2.5 Coder 7B",
    description: "Qwen 2.5 Coder mid-size model for code generation.",
    resourceType: "chat",
    family: "qwen2.5-coder",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-coder-14b": {
    id: "qwen2.5-coder-14b",
    provider: "qwen",
    name: "Qwen 2.5 Coder 14B",
    description: "Qwen 2.5 Coder mid-size model for code generation.",
    resourceType: "chat",
    family: "qwen2.5-coder",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2.5-coder-32b": {
    id: "qwen2.5-coder-32b",
    provider: "qwen",
    name: "Qwen 2.5 Coder 32B",
    description: "Qwen 2.5 Coder large model for code generation.",
    resourceType: "chat",
    family: "qwen2.5-coder",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2-vl-2b": {
    id: "qwen2-vl-2b",
    provider: "qwen",
    name: "Qwen 2 VL 2B",
    description: "Qwen 2 Vision-Language small model.",
    resourceType: "chat",
    family: "qwen2-vl",
    status: "active",
    capabilities: visionCapabilities,
    contextWindow: 32_768,
    maxOutputTokens: 4096,
  },
  "qwen2-vl-7b": {
    id: "qwen2-vl-7b",
    provider: "qwen",
    name: "Qwen 2 VL 7B",
    description: "Qwen 2 Vision-Language mid-size model.",
    resourceType: "chat",
    family: "qwen2-vl",
    status: "active",
    capabilities: visionCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "qwen2-vl-72b": {
    id: "qwen2-vl-72b",
    provider: "qwen",
    name: "Qwen 2 VL 72B",
    description: "Qwen 2 Vision-Language large model.",
    resourceType: "chat",
    family: "qwen2-vl",
    status: "active",
    capabilities: visionCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
};

export type QwenModelId = keyof typeof qwenModels;
