import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: true,
  jsonMode: true,
  objectGeneration: true,
  reasoning: false,
  embedding: false,
  structuredOutputs: true,
  supportsJSON: true,
} as const;

export const minimaxModels: Record<string, ModelDefinition> = {
  "MiniMax-M3": {
    id: "MiniMax-M3",
    provider: "minimax",
    name: "MiniMax M3",
    description: "MiniMax's flagship M3 model for advanced reasoning and multimodal tasks.",
    resourceType: "chat",
    family: "minimax-m3",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      reasoning: true,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
    aliases: ["minimax-latest"],
  },
  "MiniMax-M2.7": {
    id: "MiniMax-M2.7",
    provider: "minimax",
    name: "MiniMax M2.7",
    description: "MiniMax M2.7 general-purpose chat model.",
    resourceType: "chat",
    family: "minimax-m2.7",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "MiniMax-M2.7-highspeed": {
    id: "MiniMax-M2.7-highspeed",
    provider: "minimax",
    name: "MiniMax M2.7 Highspeed",
    description: "High-throughput variant of MiniMax M2.7.",
    resourceType: "chat",
    family: "minimax-m2.7",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "MiniMax-M2.5": {
    id: "MiniMax-M2.5",
    provider: "minimax",
    name: "MiniMax M2.5",
    description: "MiniMax M2.5 general-purpose chat model.",
    resourceType: "chat",
    family: "minimax-m2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "MiniMax-M2.5-highspeed": {
    id: "MiniMax-M2.5-highspeed",
    provider: "minimax",
    name: "MiniMax M2.5 Highspeed",
    description: "High-throughput variant of MiniMax M2.5.",
    resourceType: "chat",
    family: "minimax-m2.5",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "MiniMax-M2.1": {
    id: "MiniMax-M2.1",
    provider: "minimax",
    name: "MiniMax M2.1",
    description: "MiniMax M2.1 general-purpose chat model.",
    resourceType: "chat",
    family: "minimax-m2.1",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "MiniMax-M2.1-highspeed": {
    id: "MiniMax-M2.1-highspeed",
    provider: "minimax",
    name: "MiniMax M2.1 Highspeed",
    description: "High-throughput variant of MiniMax M2.1.",
    resourceType: "chat",
    family: "minimax-m2.1",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "MiniMax-M2": {
    id: "MiniMax-M2",
    provider: "minimax",
    name: "MiniMax M2",
    description: "MiniMax M2 general-purpose chat model.",
    resourceType: "chat",
    family: "minimax-m2",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
};

export type MiniMaxModelId = keyof typeof minimaxModels;
