import type { ModelDefinition } from "../types.js";

const chatCapabilities = {
  chat: true,
  streaming: true,
  vision: false,
  functionCalling: true,
  jsonMode: true,
  objectGeneration: true,
  reasoning: false,
  embedding: false,
  structuredOutputs: true,
  supportsJSON: true,
} as const;

export const mistralModels: Record<string, ModelDefinition> = {
  "mistral-medium-3.5": {
    id: "mistral-medium-3.5",
    provider: "mistral",
    name: "Mistral Medium 3.5",
    description: "Mistral's balanced medium model for general-purpose tasks.",
    resourceType: "chat",
    family: "mistral-medium",
    status: "active",
    capabilities: chatCapabilities,
    pricing: {
      inputTokensPerMillion: 0.4,
      outputTokensPerMillion: 2.0,
    },
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "mistral-large-3": {
    id: "mistral-large-3",
    provider: "mistral",
    name: "Mistral Large 3",
    description: "Mistral's flagship large model for complex reasoning.",
    resourceType: "chat",
    family: "mistral-large",
    status: "active",
    capabilities: {
      ...chatCapabilities,
      vision: true,
      reasoning: true,
    },
    pricing: {
      inputTokensPerMillion: 2.0,
      outputTokensPerMillion: 6.0,
    },
    contextWindow: 256_000,
    maxOutputTokens: 16_384,
  },
  "mistral-small-4": {
    id: "mistral-small-4",
    provider: "mistral",
    name: "Mistral Small 4",
    description: "Fast, efficient Mistral model for everyday tasks.",
    resourceType: "chat",
    family: "mistral-small",
    status: "active",
    capabilities: chatCapabilities,
    pricing: {
      inputTokensPerMillion: 0.1,
      outputTokensPerMillion: 0.3,
    },
    contextWindow: 128_000,
    maxOutputTokens: 8192,
  },
  "codestral-2501": {
    id: "codestral-2501",
    provider: "mistral",
    name: "Codestral 2501",
    description: "Mistral's code generation model.",
    resourceType: "chat",
    family: "codestral",
    status: "active",
    capabilities: chatCapabilities,
    pricing: {
      inputTokensPerMillion: 0.3,
      outputTokensPerMillion: 0.9,
    },
    contextWindow: 256_000,
    maxOutputTokens: 8192,
  },
  "ministral-3b": {
    id: "ministral-3b",
    provider: "mistral",
    name: "Ministral 3B",
    description: "Small edge model for on-device and low-latency use cases.",
    resourceType: "chat",
    family: "ministral",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 4096,
  },
  "ministral-8b": {
    id: "ministral-8b",
    provider: "mistral",
    name: "Ministral 8B",
    description: "Compact edge model balancing speed and capability.",
    resourceType: "chat",
    family: "ministral",
    status: "active",
    capabilities: chatCapabilities,
    contextWindow: 128_000,
    maxOutputTokens: 4096,
  },
};

export type MistralModelId = keyof typeof mistralModels;
